<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <PropertyGroup>
        <RestoreSources>
            https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json
        </RestoreSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath="" />
        <None Include="../../LICENCE" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Net.ServerSentEvents" />
    </ItemGroup>

</Project>